// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package githubapi

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// OrganizationOrganization includes the requested fields of the GraphQL type Organization.
type OrganizationOrganization struct {
	DatabaseId  *int      `json:"databaseId"`
	Id          string    `json:"id"`
	Login       string    `json:"login"`
	Name        *string   `json:"name"`
	Location    *string   `json:"location"`
	CreatedAt   time.Time `json:"createdAt"`
	AvatarUrl   string    `json:"avatarUrl"`
	WebsiteUrl  *string   `json:"websiteUrl"`
	Email       *string   `json:"email"`
	Description *string   `json:"description"`
}

// GetDatabaseId returns OrganizationOrganization.DatabaseId, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetDatabaseId() *int { return v.DatabaseId }

// GetId returns OrganizationOrganization.Id, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetId() string { return v.Id }

// GetLogin returns OrganizationOrganization.Login, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetLogin() string { return v.Login }

// GetName returns OrganizationOrganization.Name, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetName() *string { return v.Name }

// GetLocation returns OrganizationOrganization.Location, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetLocation() *string { return v.Location }

// GetCreatedAt returns OrganizationOrganization.CreatedAt, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetCreatedAt() time.Time { return v.CreatedAt }

// GetAvatarUrl returns OrganizationOrganization.AvatarUrl, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetAvatarUrl() string { return v.AvatarUrl }

// GetWebsiteUrl returns OrganizationOrganization.WebsiteUrl, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetWebsiteUrl() *string { return v.WebsiteUrl }

// GetEmail returns OrganizationOrganization.Email, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetEmail() *string { return v.Email }

// GetDescription returns OrganizationOrganization.Description, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetDescription() *string { return v.Description }

// OrganizationResponse is returned by Organization on success.
type OrganizationResponse struct {
	Organization *OrganizationOrganization `json:"organization"`
}

// GetOrganization returns OrganizationResponse.Organization, and is useful for accessing the field via an interface.
func (v *OrganizationResponse) GetOrganization() *OrganizationOrganization { return v.Organization }

// UserResponse is returned by User on success.
type UserResponse struct {
	User *UserUser `json:"user"`
}

// GetUser returns UserResponse.User, and is useful for accessing the field via an interface.
func (v *UserResponse) GetUser() *UserUser { return v.User }

// UserUser includes the requested fields of the GraphQL type User.
type UserUser struct {
	DatabaseId      *int      `json:"databaseId"`
	Id              string    `json:"id"`
	Login           string    `json:"login"`
	Name            *string   `json:"name"`
	Location        *string   `json:"location"`
	CreatedAt       time.Time `json:"createdAt"`
	AvatarUrl       string    `json:"avatarUrl"`
	WebsiteUrl      *string   `json:"websiteUrl"`
	TwitterUsername *string   `json:"twitterUsername"`
	Email           *string   `json:"email"`
	Bio             *string   `json:"bio"`
	Company         *string   `json:"company"`
}

// GetDatabaseId returns UserUser.DatabaseId, and is useful for accessing the field via an interface.
func (v *UserUser) GetDatabaseId() *int { return v.DatabaseId }

// GetId returns UserUser.Id, and is useful for accessing the field via an interface.
func (v *UserUser) GetId() string { return v.Id }

// GetLogin returns UserUser.Login, and is useful for accessing the field via an interface.
func (v *UserUser) GetLogin() string { return v.Login }

// GetName returns UserUser.Name, and is useful for accessing the field via an interface.
func (v *UserUser) GetName() *string { return v.Name }

// GetLocation returns UserUser.Location, and is useful for accessing the field via an interface.
func (v *UserUser) GetLocation() *string { return v.Location }

// GetCreatedAt returns UserUser.CreatedAt, and is useful for accessing the field via an interface.
func (v *UserUser) GetCreatedAt() time.Time { return v.CreatedAt }

// GetAvatarUrl returns UserUser.AvatarUrl, and is useful for accessing the field via an interface.
func (v *UserUser) GetAvatarUrl() string { return v.AvatarUrl }

// GetWebsiteUrl returns UserUser.WebsiteUrl, and is useful for accessing the field via an interface.
func (v *UserUser) GetWebsiteUrl() *string { return v.WebsiteUrl }

// GetTwitterUsername returns UserUser.TwitterUsername, and is useful for accessing the field via an interface.
func (v *UserUser) GetTwitterUsername() *string { return v.TwitterUsername }

// GetEmail returns UserUser.Email, and is useful for accessing the field via an interface.
func (v *UserUser) GetEmail() *string { return v.Email }

// GetBio returns UserUser.Bio, and is useful for accessing the field via an interface.
func (v *UserUser) GetBio() *string { return v.Bio }

// GetCompany returns UserUser.Company, and is useful for accessing the field via an interface.
func (v *UserUser) GetCompany() *string { return v.Company }

// __OrganizationInput is used internally by genqlient
type __OrganizationInput struct {
	Login string `json:"login"`
}

// GetLogin returns __OrganizationInput.Login, and is useful for accessing the field via an interface.
func (v *__OrganizationInput) GetLogin() string { return v.Login }

// __UserInput is used internally by genqlient
type __UserInput struct {
	Login string `json:"login"`
}

// GetLogin returns __UserInput.Login, and is useful for accessing the field via an interface.
func (v *__UserInput) GetLogin() string { return v.Login }

// The query executed by Organization.
const Organization_Operation = `
query Organization ($login: String!) {
	organization(login: $login) {
		databaseId
		id
		login
		name
		location
		createdAt
		avatarUrl
		websiteUrl
		email
		description
	}
}
`

func Organization(
	ctx_ context.Context,
	client_ graphql.Client,
	login string,
) (data_ *OrganizationResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Organization",
		Query:  Organization_Operation,
		Variables: &__OrganizationInput{
			Login: login,
		},
	}

	data_ = &OrganizationResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by User.
const User_Operation = `
query User ($login: String!) {
	user(login: $login) {
		databaseId
		id
		login
		name
		location
		createdAt
		avatarUrl
		websiteUrl
		twitterUsername
		email
		bio
		company
	}
}
`

func User(
	ctx_ context.Context,
	client_ graphql.Client,
	login string,
) (data_ *UserResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "User",
		Query:  User_Operation,
		Variables: &__UserInput{
			Login: login,
		},
	}

	data_ = &UserResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
