// Package compatibility_test holds the cross-implementation
// regression suite that pins our Go output against the upstream
// lowlighter/metrics reference. Each test under here MUST tolerate
// the absence of the upstream-derived fixtures (`./org_repo` /
// vendored evidence) by calling t.Skip, so contributor checkouts
// without the upstream submodule still pass `go test ./...`.
package compatibility_test

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mjun0812/github-metrics/internal/render"
)

const upstreamHashFixtureDir = "tests/fixtures/upstream/svg_hash"

// TestUpstreamHashCompatible asserts that render.Hash matches the
// MD5 the upstream `metrics.utils.svg.hash` produced for the same
// input. Each case lives as a (.svg, .hash) pair under
// tests/fixtures/upstream/svg_hash/.
//
// The fixtures are generated by `internal/tools/sync-fixtures
// --mode svg-hash` (Phase 6 follow-up). Until those fixtures are
// vendored, this test t.Skip's so the suite remains green for
// contributors without ./org_repo.
//
// Known divergence: the upstream hash is computed AFTER puppeteer's
// setContent normalizes the markup (attribute order, self-closing
// expansion, whitespace). Our Go Hash uses goquery, whose
// normalization rules are similar but not byte-identical. Cases that
// fail this test today should be triaged in T035 — at worst, the
// upstream hash can be re-derived through a headless browser on the fly to
// match byte-for-byte (research R-013 fallback option).
func TestUpstreamHashCompatible(t *testing.T) {
	t.Parallel()

	dir := repoRel(t, upstreamHashFixtureDir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			t.Skipf("upstream svg_hash fixtures absent (run T035 to vendor): %v", err)
		}
		t.Fatalf("read %s: %v", dir, err)
	}

	var cases []string
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".svg") {
			continue
		}
		cases = append(cases, strings.TrimSuffix(e.Name(), ".svg"))
	}
	if len(cases) == 0 {
		t.Skipf("no .svg fixtures under %s; T035 should vendor at least 3", dir)
	}

	for _, name := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			svgPath := filepath.Join(dir, name+".svg")
			hashPath := filepath.Join(dir, name+".hash")
			svg, err := os.ReadFile(svgPath)
			if err != nil {
				t.Fatalf("read %s: %v", svgPath, err)
			}
			want, err := os.ReadFile(hashPath)
			if err != nil {
				t.Fatalf("read %s: %v", hashPath, err)
			}
			got, err := render.Hash(string(svg))
			if err != nil {
				t.Fatalf("render.Hash: %v", err)
			}
			if got != strings.TrimSpace(string(want)) {
				t.Errorf("Hash drift for %s\n got:  %s\n want: %s", name, got, strings.TrimSpace(string(want)))
			}
		})
	}
}

// repoRel walks up from CWD to find a project-rooted path. Returns
// the path verbatim if the entry exists; otherwise returns the
// candidate at the repo root so callers can decide how to handle
// absence (e.g., t.Skip on fs.ErrNotExist).
func repoRel(t *testing.T, relPath string) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd: %v", err)
	}
	for {
		candidate := filepath.Join(dir, relPath)
		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
		// When walking up hits the filesystem root, return the
		// best-guess path (repo root + relPath) so callers see
		// fs.ErrNotExist on the subsequent ReadFile / ReadDir.
		parent := filepath.Dir(dir)
		if parent == dir {
			return filepath.Join(dir, relPath)
		}
		dir = parent
	}
}
