// Command gen-action-yml generates the project's action.yml from the
// embedded plugin / template metadata.yml files + core input
// definitions. The generated action.yml is the GitHub Action interface
// definition; metadata.yml is the runtime input definition. Both must
// stay in sync so callers (action.yml `with:`) and the runtime
// (INPUT_<UPPER> env) see the same input shape.
//
// Run via `make gen-action-yml`. The lefthook pre-commit hook gates
// drift (`git diff --quiet action.yml` after re-running the command).
//
// The generator walks `assets/plugins/<slug>/metadata.yml` for the
// adopted plugin set (constitution 原則 III). `core` contributes the
// shared inputs (token / user / repo / committer_* / filename /
// output / etc.) without any `plugin_<slug>` gate. `base` contributes
// its section selector and repository-fetching inputs without any
// `plugin_base` gate.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// adoptedSlugs is the canonical 21-採用 plugin directory set the
// generator walks. Two-dir entries (`languages.recent` + `.indepth`)
// share the `languages` directory; we don't iterate the dotted forms
// because their `inputs:` are already enumerated in `languages`.
//
// `base` and `core` are included for their non-plugin inputs. They do
// not expose `plugin_base` / `plugin_core` gates, but their metadata
// still defines user-facing controls such as `base` and `repositories`.
var adoptedSlugs = []string{
	"core",
	"base",
	"achievements",
	"activity",
	"calendar",
	"contributors",
	"habits",
	"header",
	"isocalendar",
	"languages",
	"notable",
	"people",
	"projects",
	"reactions",
	"repositories",
	"sponsors",
	"sponsorships",
	"stargazers",
	"starlists",
	"stars",
	"topics",
	"traffic",
}

// ghcrImageRepo is the canonical published image reference. M10 binds
// the action.yml `runs.image:` line to this when VERSION is a semver
// tag; pre-release builds fall back to the local Dockerfile path.
const ghcrImageRepo = "ghcr.io/mjun0812/github-metrics"

func main() {
	output := flag.String("output", "./action.yml", "destination path for the generated action.yml")
	assetsRoot := flag.String("assets", "./assets", "root path of the assets directory (assets/plugins/<slug>/metadata.yml)")
	flag.Parse()

	// VERSION env var (set by `make gen-action-yml VERSION=v1.0.0` or
	// by the release pipeline) toggles the `runs.image:` line:
	//   - empty / "dev" → local Dockerfile path (Dockerfile)
	//   - vX.Y.Z         → docker://ghcr.io/.../...:vX.Y.Z (pinned)
	version := os.Getenv("VERSION")

	body, err := generate(*assetsRoot, version)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-action-yml: %v\n", err)
		os.Exit(1)
	}
	if writeErr := os.WriteFile(*output, []byte(body), 0o600); writeErr != nil {
		fmt.Fprintf(os.Stderr, "gen-action-yml: write %s: %v\n", *output, writeErr)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-action-yml: wrote %s (%d bytes)\n", *output, len(body))
}

// pluginMetadata captures the slice of metadata.yml the action.yml
// generator cares about. Other fields (examples, scopes, supports,
// index, category, description) are ignored.
type pluginMetadata struct {
	Inputs yaml.Node `yaml:"inputs"`
}

// inputDef is the shape we project each metadata.yml `inputs:` entry
// into for action.yml emission. We preserve `description`, `default`,
// and `required`; the metadata-only fields (type / format / values /
// preset) are dropped because action.yml does not use them.
type inputDef struct {
	Description string
	Default     string
	Required    bool
}

// generate walks the adopted plugin metadata + emits action.yml.
// `version` toggles the `runs.image:` line:
//   - empty / "dev" → relative path to Dockerfile
//   - vX.Y.Z (semver tag) → docker://ghcr.io/.../...:<version>
func generate(assetsRoot, version string) (string, error) {
	// Header.
	var b strings.Builder
	b.WriteString("# Generated by internal/tools/gen-action-yml. DO NOT EDIT BY HAND.\n")
	b.WriteString("# Re-run via: make gen-action-yml\n")
	b.WriteString("#\n")
	b.WriteString("# This file is the GitHub Action interface for github-metrics. It mirrors\n")
	b.WriteString("# the input contract upstream lowlighter/metrics exposes, scoped to the\n")
	b.WriteString("# 21 採用 plugins (constitution 原則 III). The lefthook pre-commit hook\n")
	b.WriteString("# verifies 'git diff --quiet action.yml' after re-running the generator\n")
	b.WriteString("# so metadata.yml and action.yml never drift.\n")
	b.WriteString(`name: 'github-metrics'
description: 'Generate metrics for your GitHub profile / repository (drop-in replacement for lowlighter/metrics).'
author: 'mjun0812'
branding:
  icon: 'bar-chart-2'
  color: 'blue'

inputs:
`)

	// Walk every adopted slug and collect (name, def) pairs.
	type entry struct {
		name string
		def  inputDef
	}
	var entries []entry
	seen := map[string]bool{} // dedup by input name across slugs
	for _, slug := range adoptedSlugs {
		path := filepath.Join(assetsRoot, "plugins", slug, "metadata.yml")
		body, err := os.ReadFile(path) //nolint:gosec // assetsRoot is operator-controlled; the project's source tree
		if err != nil {
			return "", fmt.Errorf("read %s: %w", path, err)
		}
		var meta pluginMetadata
		if err := yaml.Unmarshal(body, &meta); err != nil {
			return "", fmt.Errorf("parse %s: %w", path, err)
		}
		for _, kv := range nodeMap(&meta.Inputs) {
			if seen[kv.name] {
				// Same input name declared by two plugins (rare; e.g.,
				// `dryrun` could in principle appear in multiple); we
				// keep the first-seen definition (core wins by listing
				// order, then plugins in adoptedSlugs order).
				continue
			}
			seen[kv.name] = true
			entries = append(entries, entry{name: kv.name, def: parseInputDef(kv.node)})
		}
	}

	// Sort for determinism. We use the same sort order each run so
	// the action.yml diff is meaningful.
	sort.Slice(entries, func(i, j int) bool { return entries[i].name < entries[j].name })

	for _, e := range entries {
		emitInput(&b, e.name, e.def)
	}

	// Outputs + runs footer.
	b.WriteString(`
outputs:
  metrics_url:
    description: 'URL of the generated metrics file inside the repository (when output_action committed).'
  metrics_sha:
    description: 'Render-time SHA of the generated metrics file.'

runs:
  using: 'docker'
`)
	b.WriteString(imageDirective(version))

	return b.String(), nil
}

// imageDirective emits the `runs.image:` line + its supply-chain
// comment.
//
// Pre-release (VERSION empty or "dev"): build from the local
// Dockerfile so `uses: ./` works against the source tree.
// Release (VERSION=vX.Y.Z): pin to the published GHCR tag so a
// `uses: mjun0812/github-metrics@vX.Y.Z` invocation always resolves
// to the exact image bytes published for that tag (M10 SC-006).
func imageDirective(version string) string {
	if version == "" || version == "dev" {
		return `  # Local-development fallback: build the M10 production image
  # from source. The release pipeline rewrites this line to a
  # docker:// reference pinned to the published vX.Y.Z tag when it
  # runs ` + "`VERSION=vX.Y.Z make gen-action-yml`" + `.
  image: 'Dockerfile'
`
	}
	return `  # Pinned to the published GHCR image so a
  # ` + "`uses: mjun0812/github-metrics@" + version + "`" + ` invocation always resolves
  # to the exact image bytes built for the ` + version + ` release.
  # Cosign keyless OIDC signatures (SC-004) prove provenance.
  image: 'docker://` + ghcrImageRepo + ":" + version + `'
`
}

// nodeMap returns the (key, value) pairs of a yaml.Node mapping in
// source order. Returns nil for non-mapping nodes.
type nodeKV struct {
	name string
	node *yaml.Node
}

func nodeMap(n *yaml.Node) []nodeKV {
	if n == nil || n.Kind != yaml.MappingNode {
		return nil
	}
	var out []nodeKV
	for i := 0; i+1 < len(n.Content); i += 2 {
		k := n.Content[i]
		v := n.Content[i+1]
		if k.Kind == yaml.ScalarNode {
			out = append(out, nodeKV{name: k.Value, node: v})
		}
	}
	return out
}

// parseInputDef extracts description / default / required from a
// metadata.yml input entry. Other fields (type / format / values /
// preset) are ignored — action.yml does not use them.
func parseInputDef(n *yaml.Node) inputDef {
	var d inputDef
	for _, kv := range nodeMap(n) {
		switch kv.name {
		case "description":
			if kv.node.Kind == yaml.ScalarNode {
				d.Description = strings.TrimSpace(kv.node.Value)
			}
		case "default":
			if kv.node.Kind == yaml.ScalarNode {
				d.Default = kv.node.Value
			}
		case "required":
			if kv.node.Kind == yaml.ScalarNode && kv.node.Value == "true" {
				d.Required = true
			}
		}
	}
	return d
}

// emitInput writes one action.yml input block.
func emitInput(b *strings.Builder, name string, d inputDef) {
	// Use the first line of the description; action.yml inputs only
	// support a single-line description in practical use.
	desc := firstLine(d.Description)
	if desc == "" {
		desc = name
	}
	fmt.Fprintf(b, "  %s:\n", name)
	fmt.Fprintf(b, "    description: %s\n", yamlQuote(desc))
	if d.Default != "" {
		fmt.Fprintf(b, "    default: %s\n", yamlQuote(d.Default))
	}
	fmt.Fprintf(b, "    required: %t\n", d.Required)
	b.WriteString("\n")
}

func firstLine(s string) string {
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			return line
		}
	}
	return ""
}

// yamlQuote wraps a string in single quotes, escaping inner single
// quotes per YAML 1.2 (' → ”). Sufficient for our input description
// + default strings.
func yamlQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
