query OrganizationRepositories($login: String!, $first: Int!, $after: String) {
  organization(login: $login) {
    repositories(
      first: $first
      after: $after
      orderBy: { field: UPDATED_AT, direction: DESC }
    ) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        databaseId
        id
        name
        nameWithOwner
        description
        url
        isPrivate
        isFork
        pushedAt
        updatedAt
        stargazerCount
        forkCount
        watchers {
          totalCount
        }
        primaryLanguage {
          name
          color
        }
        languages(first: 8) {
          totalCount
          totalSize
          edges {
            size
            node {
              name
              color
            }
          }
        }
      }
    }
  }
}
