query UserRepositories($login: String!, $first: Int!, $after: String) {
  user(login: $login) {
    repositories(
      first: $first
      after: $after
      ownerAffiliations: [OWNER]
      orderBy: { field: UPDATED_AT, direction: DESC }
    ) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        databaseId
        id
        name
        nameWithOwner
        description
        url
        isPrivate
        isFork
        pushedAt
        updatedAt
        stargazerCount
        forkCount
        watchers {
          totalCount
        }
        primaryLanguage {
          name
          color
        }
      }
    }
  }
}
