query UserIndepth($login: String!, $from: DateTime, $to: DateTime, $reposFirst: Int!, $reposAfter: String) {
  user(login: $login) {
    contributionsCollection(from: $from, to: $to) {
      contributionCalendar {
        totalContributions
        weeks {
          firstDay
          contributionDays {
            date
            contributionCount
            weekday
            color
          }
        }
      }
    }
    repositories(
      first: $reposFirst
      after: $reposAfter
      ownerAffiliations: [OWNER]
      orderBy: { field: UPDATED_AT, direction: DESC }
    ) {
      totalCount
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        nameWithOwner
        defaultBranchRef {
          target {
            __typename
            ... on Commit {
              history(first: 0) {
                totalCount
              }
            }
          }
        }
        issues {
          totalCount
        }
        pullRequests {
          totalCount
        }
      }
    }
  }
}
