package action

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestShouldSkip_SkipMarkerPresent(t *testing.T) {
	t.Parallel()
	path := writeEvent(t, `{"head_commit":{"message":"chore: tweak [Skip GitHub Action]"}}`)
	skip, reason := shouldSkip(path)
	if !skip {
		t.Errorf("expected skip=true; got false")
	}
	if !strings.Contains(string(reason), "[Skip GitHub Action]") {
		t.Errorf("reason should reference the marker; got %q", reason)
	}
}

func TestShouldSkip_AutoGeneratedMessage(t *testing.T) {
	t.Parallel()
	path := writeEvent(t, `{"head_commit":{"message":"Auto-generated metrics for run #42"}}`)
	skip, _ := shouldSkip(path)
	if !skip {
		t.Errorf("expected skip=true for self-triggered run")
	}
}

func TestShouldSkip_NoMarker(t *testing.T) {
	t.Parallel()
	path := writeEvent(t, `{"head_commit":{"message":"fix(api): handle EOF"}}`)
	skip, _ := shouldSkip(path)
	if skip {
		t.Errorf("expected skip=false; got true")
	}
}

func TestShouldSkip_EmptyEventPath(t *testing.T) {
	t.Parallel()
	skip, _ := shouldSkip("")
	if skip {
		t.Errorf("expected skip=false for empty event path")
	}
}

func TestShouldSkip_MissingFile(t *testing.T) {
	t.Parallel()
	skip, _ := shouldSkip("/nonexistent/event.json")
	if skip {
		t.Errorf("expected skip=false for missing event file")
	}
}

func TestShouldSkip_MalformedJSON(t *testing.T) {
	t.Parallel()
	path := writeEvent(t, "not-json")
	skip, _ := shouldSkip(path)
	if skip {
		t.Errorf("expected skip=false for malformed event JSON")
	}
}

func writeEvent(t *testing.T, body string) string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "event.json")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}
