package base

import (
	"context"
	"fmt"

	"github.com/mjun0812/github-metrics/internal/plugins"
)

// populateRepositories fetches the first page of repositories from the
// GraphQL client and folds the totals into pc.Data.Computed.Repositories.
//
// The upstream behavior pages through every owner-affiliated repository
// up to Settings.Repositories, halving the batch size on timeout. M1
// only fetches a single page (totalCount is available from the
// connection, so Count is accurate even without traversing the cursor).
// The full multi-page loop lands with the M4 plugin work that actually
// consumes per-node fields beyond what we surface here.
//
// isUser selects between the User-side and Organization-side queries
// generated by genqlient. Both expose RepositoryConnection so the
// post-processing path is identical.
func populateRepositories(ctx context.Context, pc *plugins.PluginContext, login string, first int, isUser bool) error {
	if isUser {
		resp, err := pc.GraphQL.UserRepositories(ctx, login, first)
		if err != nil {
			return fmt.Errorf("base: userRepositories(%q): %w", login, err)
		}
		if resp == nil || resp.User == nil || resp.User.Repositories == nil {
			return nil
		}
		conn := resp.User.Repositories
		pc.Data.Computed.Repositories.Count = conn.TotalCount
		for _, node := range conn.Nodes {
			if node == nil {
				continue
			}
			pc.Data.Computed.Repositories.Stargazers += node.StargazerCount
			pc.Data.Computed.Repositories.Forks += node.ForkCount
			if node.Watchers != nil {
				pc.Data.Computed.Repositories.Watchers += node.Watchers.TotalCount
			}
		}
		return nil
	}

	resp, err := pc.GraphQL.OrganizationRepositories(ctx, login, first)
	if err != nil {
		return fmt.Errorf("base: organizationRepositories(%q): %w", login, err)
	}
	if resp == nil || resp.Organization == nil || resp.Organization.Repositories == nil {
		return nil
	}
	conn := resp.Organization.Repositories
	pc.Data.Computed.Repositories.Count = conn.TotalCount
	for _, node := range conn.Nodes {
		if node == nil {
			continue
		}
		pc.Data.Computed.Repositories.Stargazers += node.StargazerCount
		pc.Data.Computed.Repositories.Forks += node.ForkCount
		if node.Watchers != nil {
			pc.Data.Computed.Repositories.Watchers += node.Watchers.TotalCount
		}
	}
	return nil
}
