#!/usr/bin/env bash
# scripts/sync-assets.sh
#
# Copy adopted-feature assets from the upstream reference checkout
# (./org_repo) into ./assets/, then record a SHA-256 lockfile so PR
# review can verify nothing else was vendored. The constitution forbids
# committing org_repo to git history; this script is the only sanctioned
# path for materializing assets/.
#
# Adopted set (from docs/design/15-selection-answer.md):
#   plugins: base, core, languages, activity, achievements, repositories,
#            isocalendar, calendar, habits, stars, topics, starlists,
#            people, notable, contributors, reactions, projects, sponsors,
#            sponsorships, stargazers, traffic
#   templates: classic, repository
#
# Unadopted plugins/templates are MUST NOT be copied — they violate
# constitution principle III (scope discipline).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${REPO_ROOT}/org_repo"
DST="${REPO_ROOT}/assets"

if [[ ! -d "${SRC}" ]]; then
    echo "sync-assets: ${SRC} not found. Place the upstream lowlighter/metrics" >&2
    echo "             checkout there and re-run." >&2
    exit 1
fi

ADOPTED_PLUGINS=(
    base
    core
    languages
    activity
    achievements
    repositories
    isocalendar
    calendar
    habits
    stars
    topics
    starlists
    people
    notable
    contributors
    reactions
    projects
    sponsors
    sponsorships
    stargazers
    traffic
)

ADOPTED_TEMPLATES=(
    classic
    repository
)

upstream_commit() {
    git -C "${SRC}" rev-parse HEAD 2>/dev/null || echo "unknown"
}

copy_dir() {
    local from="$1"
    local to="$2"
    if [[ ! -d "${from}" ]]; then
        echo "sync-assets: missing source ${from}" >&2
        return 1
    fi
    mkdir -p "${to}"
    rsync -a --delete \
        --exclude '.DS_Store' \
        --exclude 'node_modules' \
        "${from}/" "${to}/"
}

main() {
    echo "sync-assets: upstream commit $(upstream_commit)"
    echo "sync-assets: destination ${DST}"

    mkdir -p "${DST}/plugins" "${DST}/templates"

    for p in "${ADOPTED_PLUGINS[@]}"; do
        echo "  plugin: ${p}"
        copy_dir "${SRC}/source/plugins/${p}" "${DST}/plugins/${p}"
    done

    for t in "${ADOPTED_TEMPLATES[@]}"; do
        echo "  template: ${t}"
        copy_dir "${SRC}/source/templates/${t}" "${DST}/templates/${t}"
    done

    if [[ -f "${SRC}/package.json" ]]; then
        local upstream_version
        upstream_version=$(grep '"version"' "${SRC}/package.json" | head -n1 | sed -E 's/.*"version":[[:space:]]*"([^"]+)".*/\1/')
        echo "upstream:${upstream_version}" > "${DST}/version.txt"
        echo "  version: ${upstream_version}"
    fi

    {
        echo "# Generated by scripts/sync-assets.sh; do not edit by hand."
        echo "upstream_commit: $(upstream_commit)"
        echo "synced_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        echo "files:"
        find "${DST}" \( -type f -o -type l \) ! -name '.upstream.lock' ! -name '.gitkeep' -print0 |
            sort -z |
            xargs -0 shasum -a 256 |
            sed -E "s| ${DST}/(.*)$|  \1|" |
            awk '{printf "  - { sha256: %s, path: %s }\n", $1, $2}'
    } > "${DST}/.upstream.lock"

    echo "sync-assets: wrote $(wc -l < "${DST}/.upstream.lock") lock entries"
}

main "$@"
